<?php

namespace ContainerQWxfxfp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLuckyNumberTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\Type\LuckyNumberType' shared autowired service.
     *
     * @return \App\Form\Type\LuckyNumberType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/Type/LuckyNumberType.php';

        return $container->privates['App\\Form\\Type\\LuckyNumberType'] = new \App\Form\Type\LuckyNumberType();
    }
}
